services:
  db:
    image: postgres:15
    container_name: olist_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USR: postgres
      POSTGRES_PASSWORD: hakkjj97
      POSTGRES_DB: olist
    ports:
      - 5432:5432
    volumes:
      - my-db-volume:/var/lib/postgresql/data

volumes:
  my-db-volume: